#lang racket

(require "types.rkt")
(require "world.rkt")
(require "units.rkt")
(require "buildings.rkt")
(require "terrain.rkt")
(provide (all-defined-out))


(define (check-unit-hover world)
  (set-world-bg-overlay! world (make-vector
                                 (* (world-width world)
                                    (world-height world))
                                 DFT))
  (if (and
        (world-selection world)
        (unit? (world-selection world)))
      (set-move-overlay world (world-selection world) CYN)
      (for ([u (world-units world)])
        (when (and (= (world-cur-x world) (unit-x u))
                   (= (world-cur-y world) (unit-y u)))
          (set-move-overlay world u MAG)))))
(define (set-move-overlay world unit color)
  (define d (unit-range unit))
  (define h (world-height world))
  (define w (world-width world))
  (define overlay (world-bg-overlay world))
  (define (access x y) (+ x (* w y)))
  (define (fill x y range)
    (when (and (>= range 0)
            (< x w) (< y h) (>= x 0) (>= y 0))
      (vector-set! overlay (access x y) color)
      (define (next x y)
        (when (and (> range 0)
                (< x w) (< y h) (>= x 0) (>= y 0))
            (fill x y
                  (- range
                     (terrain-movement-usage
                       (unit-type unit)
                       (vector-ref (world-grid world) (access x y)))))))
      (next (- x 1) y)
      (next (+ 1 x) y)
      (next x (- y 1))
      (next x (+ 1 y))))
  (fill (unit-x unit)
        (unit-y unit)
        (unit-range unit)))

(define (do-selection world)
  (define selected #f)
  (when (and (world-selection world)
             (unit? (world-selection world)))
    (define x (world-cur-x world))
    (define y (world-cur-y world))
    (define w (world-width world))
    (when (= CYN (vector-ref (world-bg-overlay world) (+ x (* y w))))
      (set-world-menu! world (unit-options (world-selection world)))
      (set-world-menuidx! world 0))
    (set! selected #t))
  (for ([u (world-units world)])
    (when (and (not selected)
               (not (unit-has-moved u))
               (= (world-player-id world) (unit-owner-id u))
               (= (world-cur-x world) (unit-x u))
               (= (world-cur-y world) (unit-y u)))
      (set-world-selection! world u)
      (set! selected #t)))
  (for ([u (world-buildings world)])
    (when (and (not selected)
               (= (world-player-id world) (building-owner-id u))
               (= (world-cur-x world) (building-x u))
               (= (world-cur-y world) (building-y u)))
      (set-world-menu! world (building-options u))
      (set-world-menuidx! world 0)
      (set-world-selection! world u)
      (set! selected #t))))

(define (do-option world)
  (when (world-menu world)
    (if (unit? (world-selection world))
      (unit-do world (world-selection world) (world-menuidx world))
      (building-do world (world-selection world) (world-menuidx world)))
    (set-world-selection! world #f)
    (set-world-menu! world #f)))

(define (do-directional-option world)
  (when (world-menu world)
    (if (unit? (world-selection world))
      (unit-do world (world-selection world) (world-menuidx world))
      (building-do world (world-selection world) (world-menuidx world)))
    (set-world-selection! world #f)
    (set-world-menu! world #f)))


(define (update-world world)
  (check-unit-hover world))

(define (cmenu world fn)
  (define menu (world-menu world))
  (when menu
    (set-world-menuidx!
      world (modulo (fn (world-menuidx world))
                    (length menu)))))


(define (incmenu world)
  (cmenu world add1))

(define (decmenu world)
  (cmenu world sub1))
